default_context:
  project_name: 'SaaSCallAnalyzer'
  project_slug: 'saas-call-analyzer'
  domain_main: 'api.ridgeside.online'
  domain_staging: 'staging.ridgeside.online'
  domain_base_api_url: 'https://api.ridgeside.online/api/v1'
  domain_base_ws_url: 'wss://api.ridgeside.online/api/v1'
  docker_swarm_stack_name_main: 'saas-call-analyzer-prod'
  docker_swarm_stack_name_staging: 'saas-call-analyzer-staging'
  secret_key: '59861f2cc0f95029ecddeb9924133415f57c485deb11e16a7bd4ffeac8deb6d9'
  first_superuser: 'b2b.ai.agency@gmail.com'
  first_superuser_password: '2de1939473213efc940a96149ff98e5352a90a8c140b7e90154198c1416535b7'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.api.ridgeside.online", "https://staging.ridgeside.online", "https://api.ridgeside.online", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: 'smtp.gmail.com'
  smtp_user: 'b2b.ai.agency@gmail.com'
  smtp_password: 'crlapkaxupvltpnx'
  smtp_emails_from_email: 'b2b.ai.agency@gmail.com'
  smtp_emails_from_name: 'Ridgeside_AI'
  smtp_emails_to_email: 'b2b.ai.agency@gmail.com'
  postgres_password: '584244280d5c4624a8595bf6bf1ca6b39cf7e0d32abe70bb034c835bf00eface'
  pgadmin_default_user: 'b2b.ai.agency@gmail.com'
  pgadmin_default_user_password: '1cc054f788ec8e6d6291705294346e060c453fb92b76fc49d0914005f0d6e39f'
  neo4j_password: '1dcaea844a295021e45326ec875ffb1ba4323b30a459210a8db98c20f4fcc1ff'
  traefik_constraint_tag: 'traefik-public'
  traefik_constraint_tag_staging: 'traefik-staging'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:f539d97a38bac3b13766919031b6d9fd1e4d28df2cf2aa1a3c0425ffa2bf3aa7'
  sentry_dsn: ''
  docker_image_prefix: 'ridgeside.online/call-analysis/'
  docker_image_backend: 'ridgeside.online/call-analysis/backend'
  docker_image_celeryworker: 'ridgeside.online/call-analysis/celeryworker'
  docker_image_frontend: 'ridgeside.online/call-analysis/frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
