"""First migration

Revision ID: cfea420d1b5f
Revises: 
Create Date: 2025-02-18 17:08:57.510448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfea420d1b5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE user_company_name_id_seq')

    op.create_table('objections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objections_id'), 'objections', ['id'], unique=False)
    op.create_index(op.f('ix_objections_name'), 'objections', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the user was created'),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the user was last modified'),
    sa.Column('full_name', sa.String(), nullable=True, comment="User's full name"),
    sa.Column('email', sa.String(), nullable=False, comment="User's email address, used for authentication"),
    sa.Column('role', sa.String(), nullable=True, comment="User's role in the system (e.g., 'user', 'admin')"),
    sa.Column('hashed_password', sa.String(), nullable=True, comment='Hashed password for authentication'),
    sa.Column('totp_secret', sa.String(), nullable=True, comment='Secret key for TOTP two-factor authentication'),
    sa.Column('totp_counter', sa.Integer(), nullable=True, comment='Counter for TOTP authentication'),
    sa.Column('email_validated', sa.Boolean(), nullable=True, comment="Whether the user's email has been validated"),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether the user account is active'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='Whether the user has superuser privileges'),
    sa.Column('balance_rub', sa.Integer(), nullable=True, comment="User's balance in rubles"),
    sa.Column('company_name_id', sa.Integer(), server_default=sa.text("nextval('user_company_name_id_seq')"), nullable=False, comment="Unique identifier for the user's company"),
    sa.Column('gpt_filter_prompt', sa.String(), nullable=True, comment='Custom GPT filter prompt for this user'),
    sa.CheckConstraint('balance_rub >= 0', name='check_balance_non_negative'),
    sa.CheckConstraint('char_length(email) <= 255', name='check_email_max_length'),
    sa.CheckConstraint('char_length(full_name) <= 100', name='check_full_name_max_length'),
    sa.CheckConstraint('char_length(gpt_filter_prompt) <= 1000', name='check_gpt_filter_prompt_max_length'),
    sa.CheckConstraint('modified >= created', name='check_modified_after_created'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_company_name_id'), 'user', ['company_name_id'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('apikey',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('char_length(name) <= 100', name='check_name_max_length'),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > created_at', name='check_expiry_after_creation'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_key_name_user_id', 'apikey', ['name', 'user_id'], unique=True)
    op.create_index('ix_api_key_user_id_created_at', 'apikey', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_apikey_id'), 'apikey', ['id'], unique=False)
    op.create_index(op.f('ix_apikey_key_hash'), 'apikey', ['key_hash'], unique=True)
    op.create_table('call_analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manager_fio', sa.String(length=100), nullable=False),
    sa.Column('call_duration', sa.Float(precision=10, decimal_return_scale=5), nullable=True),
    sa.Column('is_manager_established_contact', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_holding_initiative', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_using_dialog_programming', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_qualifying_client', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_identifying_pain', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_presenting_product', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_showing_expertise', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_handling_objections', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_setting_next_step', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_using_client_framing', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('tone_of_voice', sa.Float(precision=10, decimal_return_scale=5), nullable=True),
    sa.Column('final_grade', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_established_contact_comment', sa.String(length=500), nullable=False),
    sa.Column('is_manager_holding_initiative_comment', sa.String(length=500), nullable=False),
    sa.Column('is_manager_using_dialog_programming_comment', sa.String(length=500), nullable=False),
    sa.Column('is_manager_qualifying_client_comment', sa.String(length=500), nullable=False),
    sa.Column('is_manager_identifying_pain_comment', sa.String(length=500), nullable=False),
    sa.Column('is_manager_presenting_product_comment', sa.String(length=500), nullable=False),
    sa.Column('is_manager_showing_expertise_comment', sa.String(length=500), nullable=False),
    sa.Column('is_manager_handling_objections_comment', sa.String(length=500), nullable=False),
    sa.Column('is_manager_setting_next_step_comment', sa.String(length=500), nullable=False),
    sa.Column('is_manager_using_client_framing_comment', sa.String(length=500), nullable=False),
    sa.Column('tone_of_voice_comment', sa.String(length=500), nullable=True),
    sa.Column('call_text', sa.String(length=5000), nullable=False),
    sa.Column('analysis_reason', sa.String(length=200), nullable=False),
    sa.Column('recommendations_how_to_work_with_client', sa.String(length=1000), nullable=False),
    sa.Column('overall_analysis', sa.String(length=1000), nullable=False),
    sa.Column('lead_url', sa.String(length=200), nullable=False),
    sa.CheckConstraint('final_grade >= 0.0 AND final_grade <= 1.0', name='check_final_grade_metric'),
    sa.CheckConstraint('is_manager_established_contact >= 0.0 AND is_manager_established_contact <= 1.0', name='check_established_contact_metric'),
    sa.CheckConstraint('is_manager_handling_objections >= 0.0 AND is_manager_handling_objections <= 1.0', name='check_handling_objections_metric'),
    sa.CheckConstraint('is_manager_holding_initiative >= 0.0 AND is_manager_holding_initiative <= 1.0', name='check_holding_initiative_metric'),
    sa.CheckConstraint('is_manager_identifying_pain >= 0.0 AND is_manager_identifying_pain <= 1.0', name='check_identifying_pain_metric'),
    sa.CheckConstraint('is_manager_presenting_product >= 0.0 AND is_manager_presenting_product <= 1.0', name='check_presenting_product_metric'),
    sa.CheckConstraint('is_manager_qualifying_client >= 0.0 AND is_manager_qualifying_client <= 1.0', name='check_qualifying_client_metric'),
    sa.CheckConstraint('is_manager_setting_next_step >= 0.0 AND is_manager_setting_next_step <= 1.0', name='check_setting_next_step_metric'),
    sa.CheckConstraint('is_manager_showing_expertise >= 0.0 AND is_manager_showing_expertise <= 1.0', name='check_showing_expertise_metric'),
    sa.CheckConstraint('is_manager_using_client_framing >= 0.0 AND is_manager_using_client_framing <= 1.0', name='check_using_client_framing_metric'),
    sa.CheckConstraint('is_manager_using_dialog_programming >= 0.0 AND is_manager_using_dialog_programming <= 1.0', name='check_using_dialog_programming_metric'),
    sa.CheckConstraint('tone_of_voice >= 0.0 AND tone_of_voice <= 1.0', name='check_tone_of_voice_metric'),
    sa.ForeignKeyConstraint(['company_name_id'], ['user.company_name_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_analysis_results_company_name_id'), 'call_analysis_results', ['company_name_id'], unique=False)
    op.create_index(op.f('ix_call_analysis_results_id'), 'call_analysis_results', ['id'], unique=False)
    op.create_table('token',
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('authenticates_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('char_length(token) <= 512', name='check_token_max_length'),
    sa.ForeignKeyConstraint(['authenticates_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=False)
    op.create_table('call_objections',
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('objection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_analysis_results.id'], ),
    sa.ForeignKeyConstraint(['objection_id'], ['objections.id'], ),
    sa.PrimaryKeyConstraint('call_id', 'objection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_objections')
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.drop_table('token')
    op.execute('DROP SEQUENCE IF EXISTS user_company_name_id_seq')
    op.drop_index(op.f('ix_call_analysis_results_id'), table_name='call_analysis_results')
    op.drop_index(op.f('ix_call_analysis_results_company_name_id'), table_name='call_analysis_results')
    op.drop_table('call_analysis_results')
    op.drop_index(op.f('ix_apikey_key_hash'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_id'), table_name='apikey')
    op.drop_index('ix_api_key_user_id_created_at', table_name='apikey')
    op.drop_index('ix_api_key_name_user_id', table_name='apikey')
    op.drop_table('apikey')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_company_name_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_objections_name'), table_name='objections')
    op.drop_index(op.f('ix_objections_id'), table_name='objections')
    op.drop_table('objections')
    # ### end Alembic commands ###
