"""fixed column tone of voice in call analysis model - now it is nullable

Revision ID: 947f01b9c74d
Revises: c41fa73fb2e4
Create Date: 2025-02-04 04:43:18.700540

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '947f01b9c74d'
down_revision = 'c41fa73fb2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_analysis_results', sa.Column('tone_of_voice', sa.Float(precision=10, decimal_return_scale=5), nullable=True))
    op.add_column('call_analysis_results', sa.Column('tone_of_voice_comment', sa.String(), nullable=True))
    op.alter_column('call_analysis_results', 'is_manager_established_contact',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_holding_initiative',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_dialog_programming',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_qualifying_client',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_identifying_pain',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_presenting_product',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_showing_expertise',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_handling_objections',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_setting_next_step',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_client_framing',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'final_grade',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_analysis_results', 'final_grade',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_client_framing',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_setting_next_step',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_handling_objections',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_showing_expertise',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_presenting_product',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_identifying_pain',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_qualifying_client',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_dialog_programming',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_holding_initiative',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_established_contact',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('call_analysis_results', 'tone_of_voice_comment')
    op.drop_column('call_analysis_results', 'tone_of_voice')
    # ### end Alembic commands ###
