"""Added columns to user and made api key

Revision ID: b07db80bfc6b
Revises: fb120f8fc198
Create Date: 2025-02-01 01:55:58.567059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07db80bfc6b'
down_revision = 'fb120f8fc198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > created_at', name='check_expiry_after_creation'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_api_key_user_id_created_at', 'apikey', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_apikey_key'), 'apikey', ['key'], unique=False)
    op.add_column('user', sa.Column('role', sa.String(), nullable=False))
    op.add_column('user', sa.Column('balance_rub', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('company_name_id', sa.String(), nullable=False))
    op.add_column('user', sa.Column('gpt_filter_prompt', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_company_name_id'), 'user', ['company_name_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_company_name_id'), table_name='user')
    op.drop_column('user', 'gpt_filter_prompt')
    op.drop_column('user', 'company_name_id')
    op.drop_column('user', 'balance_rub')
    op.drop_column('user', 'role')
    op.drop_index(op.f('ix_apikey_key'), table_name='apikey')
    op.drop_index('ix_api_key_user_id_created_at', table_name='apikey')
    op.drop_table('apikey')
    # ### end Alembic commands ###
