"""Changed column in call_analysis.py - now it is lead_url - no more bitrix

Revision ID: c41fa73fb2e4
Revises: e9ca2527cf73
Create Date: 2025-02-02 00:32:25.265676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41fa73fb2e4'
down_revision = 'e9ca2527cf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_analysis_results', sa.Column('lead_url', sa.String(), nullable=False))
    op.alter_column('call_analysis_results', 'is_manager_established_contact',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_holding_initiative',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_dialog_programming',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_qualifying_client',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_identifying_pain',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_presenting_product',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_showing_expertise',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_handling_objections',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_setting_next_step',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_client_framing',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'final_grade',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.drop_column('call_analysis_results', 'bitrix_lead_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_analysis_results', sa.Column('bitrix_lead_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('call_analysis_results', 'final_grade',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_client_framing',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_setting_next_step',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_handling_objections',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_showing_expertise',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_presenting_product',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_identifying_pain',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_qualifying_client',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_dialog_programming',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_holding_initiative',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_established_contact',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('call_analysis_results', 'lead_url')
    # ### end Alembic commands ###
