"""added call_duration to model

Revision ID: ca2d08acf3b0
Revises: e9da05c23986
Create Date: 2025-02-09 03:05:09.185578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2d08acf3b0'
down_revision = 'e9da05c23986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_analysis_results', sa.Column('call_duration', sa.Float(precision=10, decimal_return_scale=5), nullable=True))
    op.alter_column('call_analysis_results', 'is_manager_established_contact',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_holding_initiative',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_dialog_programming',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_qualifying_client',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_identifying_pain',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_presenting_product',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_showing_expertise',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_handling_objections',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_setting_next_step',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_client_framing',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'tone_of_voice',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=True)
    op.alter_column('call_analysis_results', 'final_grade',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_analysis_results', 'final_grade',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'tone_of_voice',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('call_analysis_results', 'is_manager_using_client_framing',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_setting_next_step',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_handling_objections',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_showing_expertise',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_presenting_product',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_identifying_pain',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_qualifying_client',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_dialog_programming',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_holding_initiative',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_established_contact',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('call_analysis_results', 'call_duration')
    # ### end Alembic commands ###
