"""Add separate id and key fields in APIKey

Revision ID: e379f1049adf
Revises: 135952e97081
Create Date: 2025-02-08 10:45:44.447708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e379f1049adf'
down_revision = '135952e97081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_index('ix_apikey_key', table_name='apikey')
    op.create_index(op.f('ix_apikey_key'), 'apikey', ['key'], unique=True)
    op.create_index('ix_api_key_name', 'apikey', ['name'], unique=False)
    op.create_index(op.f('ix_apikey_id'), 'apikey', ['id'], unique=False)
    op.alter_column('call_analysis_results', 'is_manager_established_contact',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_holding_initiative',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_dialog_programming',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_qualifying_client',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_identifying_pain',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_presenting_product',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_showing_expertise',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_handling_objections',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_setting_next_step',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_client_framing',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'tone_of_voice',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=True)
    op.alter_column('call_analysis_results', 'final_grade',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('user', 'created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the user was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'modified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the user was last modified',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               comment="User's full name",
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               comment="User's email address, used for authentication",
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment="User's role in the system (e.g., 'user', 'admin')")
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment='Hashed password for authentication',
               existing_nullable=True)
    op.alter_column('user', 'totp_secret',
               existing_type=sa.VARCHAR(),
               comment='Secret key for TOTP two-factor authentication',
               existing_nullable=True)
    op.alter_column('user', 'totp_counter',
               existing_type=sa.INTEGER(),
               comment='Counter for TOTP authentication',
               existing_nullable=True)
    op.alter_column('user', 'email_validated',
               existing_type=sa.BOOLEAN(),
               comment="Whether the user's email has been validated",
               existing_nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether the user account is active',
               existing_nullable=False)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment='Whether the user has superuser privileges',
               existing_nullable=False)
    op.alter_column('user', 'balance_rub',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment="User's balance in rubles")
    op.alter_column('user', 'company_name_id',
               existing_type=sa.INTEGER(),
               comment="Unique identifier for the user's company",
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_company_name_id_seq'::regclass)"))
    op.alter_column('user', 'gpt_filter_prompt',
               existing_type=sa.VARCHAR(),
               comment='Custom GPT filter prompt for this user',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gpt_filter_prompt',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Custom GPT filter prompt for this user',
               existing_nullable=True)
    op.alter_column('user', 'company_name_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Unique identifier for the user's company",
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_company_name_id_seq'::regclass)"))
    op.alter_column('user', 'balance_rub',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment="User's balance in rubles")
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the user has superuser privileges',
               existing_nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the user account is active',
               existing_nullable=False)
    op.alter_column('user', 'email_validated',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="Whether the user's email has been validated",
               existing_nullable=False)
    op.alter_column('user', 'totp_counter',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Counter for TOTP authentication',
               existing_nullable=True)
    op.alter_column('user', 'totp_secret',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Secret key for TOTP two-factor authentication',
               existing_nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Hashed password for authentication',
               existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment="User's role in the system (e.g., 'user', 'admin')")
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="User's email address, used for authentication",
               existing_nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="User's full name",
               existing_nullable=True)
    op.alter_column('user', 'modified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the user was last modified',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the user was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('call_analysis_results', 'final_grade',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'tone_of_voice',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('call_analysis_results', 'is_manager_using_client_framing',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_setting_next_step',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_handling_objections',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_showing_expertise',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_presenting_product',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_identifying_pain',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_qualifying_client',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_dialog_programming',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_holding_initiative',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_established_contact',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_apikey_id'), table_name='apikey')
    op.drop_index('ix_api_key_name', table_name='apikey')
    op.drop_index(op.f('ix_apikey_key'), table_name='apikey')
    op.create_index('ix_apikey_key', 'apikey', ['key'], unique=False)
    op.drop_column('apikey', 'id')
    # ### end Alembic commands ###
