"""make_user_fields_nullable

Revision ID: e9da05c23986
Revises: e379f1049adf
Create Date: 2025-02-09 00:13:22.792856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9da05c23986'
down_revision = 'e379f1049adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_analysis_results', 'is_manager_established_contact',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_holding_initiative',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_dialog_programming',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_qualifying_client',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_identifying_pain',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_presenting_product',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_showing_expertise',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_handling_objections',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_setting_next_step',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_client_framing',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'tone_of_voice',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=True)
    op.alter_column('call_analysis_results', 'final_grade',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=5),
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment="User's role in the system (e.g., 'user', 'admin')")
    op.alter_column('user', 'email_validated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment="Whether the user's email has been validated")
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Whether the user account is active')
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Whether the user has superuser privileges')
    op.alter_column('user', 'balance_rub',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment="User's balance in rubles")
    op.alter_column('user', 'company_name_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment="Unique identifier for the user's company",
               existing_server_default=sa.text("nextval('user_company_name_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'company_name_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment="Unique identifier for the user's company",
               existing_server_default=sa.text("nextval('user_company_name_id_seq'::regclass)"))
    op.alter_column('user', 'balance_rub',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment="User's balance in rubles")
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='Whether the user has superuser privileges')
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='Whether the user account is active')
    op.alter_column('user', 'email_validated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment="Whether the user's email has been validated")
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment="User's role in the system (e.g., 'user', 'admin')")
    op.alter_column('call_analysis_results', 'final_grade',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'tone_of_voice',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('call_analysis_results', 'is_manager_using_client_framing',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_setting_next_step',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_handling_objections',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_showing_expertise',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_presenting_product',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_identifying_pain',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_qualifying_client',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_using_dialog_programming',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_holding_initiative',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('call_analysis_results', 'is_manager_established_contact',
               existing_type=sa.Float(precision=10, decimal_return_scale=5),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
