"""Added call analysis and objections table

Revision ID: f831c5fb9525
Revises: a43cfd29e3ff
Create Date: 2025-02-01 02:26:07.444831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f831c5fb9525'
down_revision = 'a43cfd29e3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objections_id'), 'objections', ['id'], unique=False)
    op.create_index(op.f('ix_objections_name'), 'objections', ['name'], unique=True)
    op.create_table('call_analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manager_fio', sa.String(), nullable=False),
    sa.Column('is_manager_established_contact', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_holding_initiative', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_using_dialog_programming', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_qualifying_client', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_identifying_pain', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_presenting_product', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_showing_expertise', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_handling_objections', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_setting_next_step', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_using_client_framing', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('final_grade', sa.Float(precision=10, decimal_return_scale=5), nullable=False),
    sa.Column('is_manager_established_contact_comment', sa.String(), nullable=False),
    sa.Column('is_manager_holding_initiative_comment', sa.String(), nullable=False),
    sa.Column('is_manager_using_dialog_programming_comment', sa.String(), nullable=False),
    sa.Column('is_manager_qualifying_client_comment', sa.String(), nullable=False),
    sa.Column('is_manager_identifying_pain_comment', sa.String(), nullable=False),
    sa.Column('is_manager_presenting_product_comment', sa.String(), nullable=False),
    sa.Column('is_manager_showing_expertise_comment', sa.String(), nullable=False),
    sa.Column('is_manager_handling_objections_comment', sa.String(), nullable=False),
    sa.Column('is_manager_setting_next_step_comment', sa.String(), nullable=False),
    sa.Column('is_manager_using_client_framing_comment', sa.String(), nullable=False),
    sa.Column('call_text', sa.String(), nullable=False),
    sa.Column('analysis_reason', sa.String(), nullable=False),
    sa.Column('recommendations_how_to_work_with_client', sa.String(), nullable=False),
    sa.Column('overall_analysis', sa.String(), nullable=False),
    sa.Column('bitrix_lead_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_name_id'], ['user.company_name_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_analysis_results_company_name_id'), 'call_analysis_results', ['company_name_id'], unique=False)
    op.create_index(op.f('ix_call_analysis_results_id'), 'call_analysis_results', ['id'], unique=False)
    op.create_table('call_objections',
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('objection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_analysis_results.id'], ),
    sa.ForeignKeyConstraint(['objection_id'], ['objections.id'], ),
    sa.PrimaryKeyConstraint('call_id', 'objection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_objections')
    op.drop_index(op.f('ix_call_analysis_results_id'), table_name='call_analysis_results')
    op.drop_index(op.f('ix_call_analysis_results_company_name_id'), table_name='call_analysis_results')
    op.drop_table('call_analysis_results')
    op.drop_index(op.f('ix_objections_name'), table_name='objections')
    op.drop_index(op.f('ix_objections_id'), table_name='objections')
    op.drop_table('objections')
    # ### end Alembic commands ###
